# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66201d62b06069c79b3bc6d7081b60924f6790576b5db101b5c786910a687ba7c961f99bac7d6c619f222188a077291ade52c0cf4d541e9669a1245d9fd9b5c6

test:
  secret_key_base: 306a439911b3372b520c577d6768655359f3009c4f9a034312c6322d54e53cf9b7ff6471e3df8beabda78dfb7df35dab9c3a62561d1a899e74f067d24c117b95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
